export const GET_USER_AUTHENTICATION_REQUEST =
  'GET_USER_AUTHENTICATION_REQUEST';
export const GET_USER_AUTHENTICATION = 'GET_USER_AUTHENTICATION';
export const GET_USER_AUTHENTICATION_FAIL = 'GET_USER_AUTHENTICATION_FAIL';
export const RESET_USER_DATA = 'RESET_USER_DATA';
